### ISSUE TITLE
Settings side bar is transparent on firefox

### ISSUE THREAD

**Issue by opensas** [Kamona-WD/starter-dashboard-layout#1]
![image](https://user-images.githubusercontent.com/481687/102047124-7c636700-3dbb-11eb-8266-1071374bbbfe.png)

running on firefox 83.0 on ubuntu 18.04

**Comment by Kamona-WD** [comment]
From version 70: backdrop-filter feature is behind the layout.css.backdrop-filter.enabled preference (needs to be set to true) and the gfx.webrender.all preference (needs to be set to true). [see link](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter)
I will remove backdrop-filter effect  from settings panel and add backdrop shadow
thanks for participate
